In [1]:
from __future__ import print_function
import sklearn
import sklearn.datasets

import sklearn.ensemble
import numpy as np
import lime


import lime.lime_tabular
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
from xgboost import XGBClassifier
import pandas as pd

# np.random.seed(1)

In [2]:
feature_names = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Marital Status","Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss","Hours per week", "Country"]
feature_names_ = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Marital Status","Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss","Hours per week", "Country", "Target"]


In [3]:
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)
data

array([['39', 'State-gov', '77516', ..., '40', 'United-States', '<=50K'],
       ['50', 'Self-emp-not-inc', '83311', ..., '13', 'United-States',
        '<=50K'],
       ['38', 'Private', '215646', ..., '40', 'United-States', '<=50K'],
       ...,
       ['58', 'Private', '151910', ..., '40', 'United-States', '<=50K'],
       ['22', 'Private', '201490', ..., '20', 'United-States', '<=50K'],
       ['52', 'Self-emp-inc', '287927', ..., '40', 'United-States',
        '>50K']], dtype='<U26')

In [4]:
df = pd.DataFrame(data=data,  columns=feature_names_)

In [5]:
labels = data[:,14]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]


['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


In [6]:
categorical_features = [1,3,5, 6,7,8,9,13]
m = 1

In [7]:
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])

['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['4' '2' '0' ... '6' '4' '2']
['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['4' '4' '4' ... '4' '4' '4']
['Amer-Indian-Eskimo' 'Asian-Pac-Islander' 'Black' 'Other' 'White']
['1' '1' '1' ... '0' '1' 

In [8]:
data = data.astype(float)
print(data)


[[3.90000e+01 7.00000e+00 7.75160e+04 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 [5.00000e+01 6.00000e+00 8.33110e+04 ... 0.00000e+00 1.30000e+01
  3.90000e+01]
 [3.80000e+01 4.00000e+00 2.15646e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 ...
 [5.80000e+01 4.00000e+00 1.51910e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 [2.20000e+01 4.00000e+00 2.01490e+05 ... 0.00000e+00 2.00000e+01
  3.90000e+01]
 [5.20000e+01 5.00000e+00 2.87927e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]]


In [9]:
df = pd.DataFrame(data=data,  columns=feature_names)
df.corr()


Age  Workclass    fnlwgt  Education  Education-Num  \
Age             1.000000   0.003787 -0.076646  -0.010508       0.036527   
Workclass       0.003787   1.000000 -0.016656   0.023513       0.052085   
fnlwgt         -0.076646  -0.016656  1.000000  -0.028145      -0.043195   
Education      -0.010508   0.023513 -0.028145   1.000000       0.359153   
Education-Num   0.036527   0.052085 -0.043195   0.359153       1.000000   
Marital Status -0.266288  -0.064731  0.028153  -0.038407      -0.069304   
Occupation     -0.020947   0.254892  0.001597  -0.021260       0.109697   
Relationship   -0.263698  -0.090461  0.008931  -0.010876      -0.094153   
Race            0.028718   0.049742 -0.021291   0.014131       0.031838   
Sex             0.088832   0.095981  0.026858  -0.027356       0.012280   
Capital Gain    0.077674   0.033835  0.000432   0.030046       0.122630   
Capital Loss    0.057775   0.012216 -0.010252   0.016746       0.079923   
Hours per week  0.068756   0.138962 -0.018768   0.055510       0.148123   
Country        -0.001151  -0.007690 -0.051966   0.064288       0.050840   

                Marital Status  Occupation  Relationship      Race       Sex  \
Age                  -0.266288   -0.020947     -0.263698  0.028718  0.088832   
Workclass            -0.064731    0.254892     -0.090461  0.049742  0.095981   
fnlwgt                0.028153    0.001597      0.008931 -0.021291  0.026858   
Education            -0.038407   -0.021260     -0.010876  0.014131 -0.027356   
Education-Num        -0.069304    0.109697     -0.094153  0.031838  0.012280   
Marital Status        1.000000   -0.009654      0.185451 -0.068013 -0.129314   
Occupation           -0.009654    1.000000     -0.075607  0.006763  0.080296   
Relationship          0.185451   -0.075607      1.000000 -0.116055 -0.582454   
Race                 -0.068013    0.006763     -0.116055  1.000000  0.087204   
Sex                  -0.129314    0.080296     -0.582454  0.087204  1.000000   
Capital Gain         -0.043393    0.025505     -0.057919  0.011145  0.048480   
Capital Loss         -0.034187    0.017987     -0.061062  0.018899  0.045567   
Hours per week       -0.190519    0.080383     -0.248974  0.041910  0.229309   
Country              -0.023819   -0.012543     -0.005507  0.137852 -0.008119   

                Capital Gain  Capital Loss  Hours per week   Country  
Age                 0.077674      0.057775        0.068756 -0.001151  
Workclass           0.033835      0.012216        0.138962 -0.007690  
fnlwgt              0.000432     -0.010252       -0.018768 -0.051966  
Education           0.030046      0.016746        0.055510  0.064288  
Education-Num       0.122630      0.079923        0.148123  0.050840  
Marital Status     -0.043393     -0.034187       -0.190519 -0.023819  
Occupation          0.025505      0.017987        0.080383 -0.012543  
Relationship       -0.057919     -0.061062       -0.248974 -0.005507  
Race                0.011145      0.018899        0.041910  0.137852  
Sex                 0.048480      0.045567        0.229309 -0.008119  
Capital Gain        1.000000     -0.031615        0.078409 -0.001982  
Capital Loss       -0.031615      1.000000        0.054256  0.000419  
Hours per week      0.078409      0.054256        1.000000 -0.002671  
Country            -0.001982      0.000419       -0.002671  1.000000

In [10]:
from sklearn.compose import ColumnTransformer

encoder = ColumnTransformer(
    [('one_hot_encoder', sklearn.preprocessing.OneHotEncoder(categories='auto'),  [1,3,5, 6,7,8,9,13])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)


In [11]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.2)

In [12]:
from imblearn.over_sampling import SMOTE
unique, counts = np.unique(labels_train, return_counts=True)
print(dict(zip(unique, counts)))
sm = SMOTE(ratio='auto')
train_res, labels_train_res = sm.fit_sample(train, labels_train)
unique, counts = np.unique(labels_train_res, return_counts=True)
print(dict(zip(unique, counts)))

{0: 19694, 1: 6354}
{0: 19694, 1: 19694}


In [13]:
data = []
data = np.concatenate([train_res,test])
data.shape


(45901, 14)

In [14]:
encoder.fit(data)
encoded_train = encoder.transform(train_res)
encoded_test = encoder.transform(test)

In [15]:
from sklearn.linear_model import LogisticRegression
gbtree =  LogisticRegression()
gbtree.fit(encoded_train, labels_train_res)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
def to_labels(pos_probs, threshold):
    return (pos_probs >= threshold).astype('int')


In [17]:
data[1]

array([5.4000e+01, 6.0000e+00, 1.0501e+05, 9.0000e+00, 1.3000e+01,
       2.0000e+00, 4.0000e+00, 0.0000e+00, 4.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 4.0000e+01, 3.9000e+01])

In [18]:
from pylab import *
yhat = gbtree.predict_proba(encoded_test)
probs = yhat[:, 1]
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))


Threshold=0.401, F-Score=0.66528


In [19]:
thresholds[ix]

0.401

In [20]:
sklearn.metrics.accuracy_score(labels_test,to_labels(probs, thresholds[ix]))


0.8265008444649163

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
predict_fn = lambda x: gbtree.predict_proba(encoder.transform(x)).astype(float)


In [23]:
print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs, thresholds[ix])))



Accuracy is  82.65008444649163


Precision Value is
               precision    recall  f1-score   support

           0       0.92      0.85      0.88      5026
           1       0.59      0.76      0.67      1487

   micro avg       0.83      0.83      0.83      6513
   macro avg       0.76      0.80      0.77      6513
weighted avg       0.85      0.83      0.83      6513



In [24]:
sklearn.metrics.roc_curve( labels_test, to_labels(probs, thresholds[ix]))

(array([0.        , 0.15240748, 1.        ]),
 array([0.        , 0.75521184, 1.        ]),
 array([2, 1, 0]))

### Another model trained after removing column 'Sex'

In [25]:
feature_names1 = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Marital Status","Occupation",
                  "Relationship", "Race", "Capital Gain", "Capital Loss","Hours per week", "Country"]
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)

In [26]:
data = np.delete(data, 9, axis = 1)


In [27]:
labels = data[:,13]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]
data.shape


['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


(32561, 13)

In [28]:
categorical_features = [1,3,5, 6,7,8,12]
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])
data = data.astype(float)

['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['4' '2' '0' ... '6' '4' '2']
['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['4' '4' '4' ... '4' '4' '4']
['Amer-Indian-Eskimo' 'Asian-Pac-Islander' 'Black' 'Other' 'White']
['39' '39' '39' ... '39' 

In [29]:
from sklearn.compose import ColumnTransformer

encoder1 = ColumnTransformer(
    [('one_hot_encoder', sklearn.preprocessing.OneHotEncoder(categories='auto'),  [1,3,5, 6,7,8,12])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
encoder1.fit(data)

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('one_hot_encoder', OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True), [1, 3, 5, 6, 7, 8, 12])])

In [30]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.2)

In [31]:
from imblearn.over_sampling import SMOTE
unique, counts = np.unique(labels_train, return_counts=True)
print(dict(zip(unique, counts)))
sm = SMOTE(ratio='auto')
train_res, labels_train_res = sm.fit_sample(train, labels_train)
unique, counts = np.unique(labels_train_res, return_counts=True)
print(dict(zip(unique, counts)))

{0: 19694, 1: 6354}
{0: 19694, 1: 19694}


In [32]:
data = []
data = np.concatenate([train_res,test])
data.shape


(45901, 13)

In [33]:
encoder1 = encoder1.fit(data)
encoded_train = encoder1.transform(train_res)
encoded_test = encoder1.transform(test)
d1 = encoder1.transform(data)

In [34]:

gbtree1 = LogisticRegression()
gbtree1.fit(encoded_train, labels_train_res)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [35]:
from pylab import *
yhat = gbtree1.predict_proba(encoded_test)
probs = yhat[:, 1]
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

Threshold=0.378, F-Score=0.67009


In [36]:
thresholds[ix]

0.378

In [37]:
sklearn.metrics.accuracy_score(labels_test,to_labels(probs, thresholds[ix] ) )


0.8324888684170121

In [38]:
gbtree1.predict_proba(d1[20])

array([[0.90784903, 0.09215097]])

In [39]:
def predict_fn1(x):
    x = np.delete(x, 9, axis = 1)
    return gbtree1.predict_proba(encoder1.transform(x)).astype(float)

In [40]:
from sklearn.metrics import confusion_matrix
result1= confusion_matrix(labels_test, to_labels(probs,thresholds[ix]))
result1

array([[4314,  712],
       [ 379, 1108]])

In [41]:
print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs, thresholds[ix])))


Accuracy is  83.24888684170121


Precision Value is
               precision    recall  f1-score   support

           0       0.92      0.86      0.89      5026
           1       0.61      0.75      0.67      1487

   micro avg       0.83      0.83      0.83      6513
   macro avg       0.76      0.80      0.78      6513
weighted avg       0.85      0.83      0.84      6513



### Another model trained after removing column 'Race'


In [42]:
feature_names2 = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Marital Status","Occupation", "Relationship","Sex", "Capital Gain", "Capital Loss","Hours per week", "Country"]
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)

In [43]:
data = np.delete(data, 8, axis = 1)

In [44]:
labels = data[:,13]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]
data.shape

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


(32561, 13)

In [45]:
categorical_features = [1,3,5, 6,7,8,12]
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])
data = data.astype(float)


['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['4' '2' '0' ... '6' '4' '2']
['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['1' '1' '1' ... '0' '1' '0']
['Female' 'Male']
['39' '39' '39' ... '39' '39' '39']
['?' 'Cambodia' 'Canada' 'China' 'Colum

In [46]:
data = data.astype(float)

In [47]:
from sklearn.compose import ColumnTransformer

encoder2 = ColumnTransformer(
    [('one_hot_encoder', sklearn.preprocessing.OneHotEncoder(categories='auto'),  [1,3,5, 6,7,8,12])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
encoder2.fit(data)

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('one_hot_encoder', OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True), [1, 3, 5, 6, 7, 8, 12])])

In [48]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.2)

In [49]:
from imblearn.over_sampling import SMOTE
unique, counts = np.unique(labels_train, return_counts=True)
print(dict(zip(unique, counts)))
sm = SMOTE(ratio='auto')
train_res, labels_train_res = sm.fit_sample(train, labels_train)
unique, counts = np.unique(labels_train_res, return_counts=True)
print(dict(zip(unique, counts)))

{0: 19694, 1: 6354}
{0: 19694, 1: 19694}


In [50]:
data = []
data = np.concatenate([train_res,test])
data.shape


(45901, 13)

In [51]:
encoder2 = encoder2.fit(data)
encoded_train = encoder2.transform(train_res)
encoded_test = encoder2.transform(test)
d2 = encoder2.transform(data)

In [52]:
gbtree2 = LogisticRegression()
gbtree2.fit(encoded_train, labels_train_res)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [53]:
from pylab import *
yhat = gbtree2.predict_proba(encoded_test)
probs = yhat[:, 1]
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

Threshold=0.440, F-Score=0.66811


In [54]:
thresholds[ix]

0.44

In [55]:
sklearn.metrics.accuracy_score(labels_test,to_labels(probs,thresholds[ix]) )

0.8354061108552127

In [56]:
gbtree2.predict_proba(d2[20])

array([[0.89001596, 0.10998404]])

In [57]:
def predict_fn2(x):
    x = np.delete(x, 8, axis = 1)
    return gbtree2.predict_proba(encoder2.transform(x)).astype(float)

In [58]:
from sklearn.metrics import confusion_matrix
result2= confusion_matrix(labels_test, to_labels(probs, 0.301))
result2

array([[3923, 1103],
       [ 233, 1254]])

In [59]:
print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs, thresholds[ix])))


Accuracy is  83.54061108552126


Precision Value is
               precision    recall  f1-score   support

           0       0.91      0.87      0.89      5026
           1       0.62      0.73      0.67      1487

   micro avg       0.84      0.84      0.84      6513
   macro avg       0.77      0.80      0.78      6513
weighted avg       0.85      0.84      0.84      6513



### Another model after removing Marital Status

In [60]:
feature_names4 = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num","Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss","Hours per week", "Country"]
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)

In [61]:
data = np.delete(data, 5, axis = 1)

In [62]:
labels = data[:,13]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]
data.shape

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


(32561, 13)

In [63]:
categorical_features = [1,3,5, 6,7,8,12]
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])
data = data.astype(float)

['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['4' '4' '4' ... '4' '4' '4']
['Amer-Indian-Eskimo' 'Asian-Pac-Islander' 'Black' 'Other' 'White']
['1' '1' '1' ... '0' '1' '0']
['Female' 'Male']
['39' '39' '39' ... '39' '39' '39']
['?' 'Cambodia' 'Canada' 'China' 'Columbia' 'Cuba' 'Dominican-Republic'
 'Ecuador' 'El-S

In [64]:
from sklearn.compose import ColumnTransformer

encoder4 = ColumnTransformer(
    [('one_hot_encoder', sklearn.preprocessing.OneHotEncoder(categories='auto'),  [1,3,5, 6,7,8,12])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
encoder4.fit(data)

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('one_hot_encoder', OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True), [1, 3, 5, 6, 7, 8, 12])])

In [65]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.20)

In [66]:
from imblearn.over_sampling import SMOTE
unique, counts = np.unique(labels_train, return_counts=True)
print(dict(zip(unique, counts)))
sm = SMOTE(ratio='auto')
train_res, labels_train_res = sm.fit_sample(train, labels_train)
unique, counts = np.unique(labels_train_res, return_counts=True)
print(dict(zip(unique, counts)))

{0: 19694, 1: 6354}
{0: 19694, 1: 19694}


In [67]:
data = []
data = np.concatenate([train_res,test])
data.shape


(45901, 13)

In [68]:
encoder4 = encoder4.fit(data)
encoded_train = encoder4.transform(train_res)
encoded_test = encoder4.transform(test)
d4 = encoder4.transform(data)

In [69]:
gbtree4 = LogisticRegression()
gbtree4.fit(encoded_train, labels_train_res)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [70]:
from pylab import *
yhat = gbtree4.predict_proba(encoded_test)
probs = yhat[:, 1]
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

Threshold=0.426, F-Score=0.66980


In [71]:
thresholds[ix]

0.426

In [72]:
sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))


0.8380162751420236

In [73]:
gbtree4.predict_proba(d4[20])
def predict_fn4(x):
    x = np.delete(x,5,axis =1)
    return gbtree4.predict_proba(encoder4.transform(x)).astype(float)

In [74]:
from sklearn.metrics import confusion_matrix
result4= confusion_matrix(labels_test, to_labels(probs, thresholds[ix]))
result4

array([[4388,  638],
       [ 417, 1070]])

In [75]:

print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs,thresholds[ix])))


Accuracy is  83.80162751420237


Precision Value is
               precision    recall  f1-score   support

           0       0.91      0.87      0.89      5026
           1       0.63      0.72      0.67      1487

   micro avg       0.84      0.84      0.84      6513
   macro avg       0.77      0.80      0.78      6513
weighted avg       0.85      0.84      0.84      6513



### Another model trained after removing column 'Race' and 'Sex' and 'Marital Status'


In [76]:
feature_names3 = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num","Occupation", "Relationship", "Capital Gain", "Capital Loss","Hours per week", "Country"]
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)

In [77]:
data = np.delete(data, 8, axis = 1)
data = np.delete(data, 8, axis = 1)
data = np.delete(data, 5, axis = 1)

In [78]:
labels = data[:,11]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]
data.shape

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


(32561, 11)

In [79]:
categorical_features = [1,3,5, 6,10]
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])


['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['39' '39' '39' ... '39' '39' '39']
['?' 'Cambodia' 'Canada' 'China' 'Columbia' 'Cuba' 'Dominican-Republic'
 'Ecuador' 'El-Salvador' 'England' 'France' 'Germany' 'Greece' 'Guatemala'
 'Haiti' 'Holand-Netherlands' 'Honduras' 'Hong' 'Hungary' 'India' 'Iran'
 'Ireland' 'It

In [80]:
data = data.astype(float)
# d_male = d_male.astype(float)
# d_female = d_female.astype(float)

In [81]:
from sklearn.compose import ColumnTransformer

encoder3 = ColumnTransformer(
    [('one_hot_encoder', sklearn.preprocessing.OneHotEncoder(categories='auto'),  [1,3,5, 6,10])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)
encoder3.fit(data)

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('one_hot_encoder', OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True), [1, 3, 5, 6, 10])])

In [82]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.20)

In [83]:
from imblearn.over_sampling import SMOTE
unique, counts = np.unique(labels_train, return_counts=True)
print(dict(zip(unique, counts)))
sm = SMOTE(ratio='auto')
train_res, labels_train_res = sm.fit_sample(train, labels_train)
unique, counts = np.unique(labels_train_res, return_counts=True)
print(dict(zip(unique, counts)))

{0: 19694, 1: 6354}
{0: 19694, 1: 19694}


In [84]:
data = []
data = np.concatenate([train_res,test])
data.shape

(45901, 11)

In [85]:
encoder3 = encoder3.fit(data)
encoded_train = encoder3.transform(train_res)
encoded_test = encoder3.transform(test)
d3 = encoder3.transform(data)

In [86]:
gbtree3 =LogisticRegression()
gbtree3.fit(encoded_train, labels_train_res)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [87]:
from pylab import *
yhat = gbtree3.predict_proba(encoded_test)
probs = yhat[:, 1]
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

Threshold=0.364, F-Score=0.66400


In [88]:
sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))


0.8197451251343467

In [89]:
gbtree3.predict_proba(d3[20])
def predict_fn3(x):
    x = np.delete(x, 8, axis = 1)
    x = np.delete(x,8,axis =1)
    x = np.delete(x,5,axis =1)
    return gbtree3.predict_proba(encoder3.transform(x)).astype(float)

In [90]:
thresholds[ix]


0.364

In [91]:
print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs, thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs, thresholds[ix])))


Accuracy is  81.97451251343468


Precision Value is
               precision    recall  f1-score   support

           0       0.93      0.83      0.88      5026
           1       0.58      0.78      0.66      1487

   micro avg       0.82      0.82      0.82      6513
   macro avg       0.75      0.81      0.77      6513
weighted avg       0.85      0.82      0.83      6513



### Ensemble of 4 models

In [92]:
feature_names = ["Age", "Workclass", "fnlwgt", "Education", "Education-Num", "Marital Status","Occupation", "Relationship", "Race", "Sex", "Capital Gain", "Capital Loss","Hours per week", "Country"]
data = np.genfromtxt('adult.data', delimiter=', ', dtype=str)


In [93]:
labels = data[:,14]
print(labels)
le= sklearn.preprocessing.LabelEncoder()
le.fit(labels)
labels = le.transform(labels)
print(labels)
class_names = le.classes_
print(class_names)
data = data[:,:-1]
data.shape

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '>50K']
[0 0 0 ... 0 0 1]
['<=50K' '>50K']


(32561, 14)

In [94]:
categorical_features = [1,3,5, 6,7,8,9,13]

In [95]:
categorical_names = {}
for feature in categorical_features:
    le = sklearn.preprocessing.LabelEncoder()
    le.fit(data[:, feature])
    data[:, feature] = le.transform(data[:, feature])
    print(data[:, feature])
    categorical_names[feature] = le.classes_
    print(categorical_names[feature])

['7' '6' '4' ... '4' '4' '5']
['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
['9' '9' '11' ... '11' '11' '11']
['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
['4' '2' '0' ... '6' '4' '2']
['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
['1' '4' '6' ... '1' '1' '4']
['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
['1' '0' '1' ... '4' '3' '5']
['Husband' 'Not-in-family' 'Other-relative' 'Own-child' 'Unmarried' 'Wife']
['4' '4' '4' ... '4' '4' '4']
['Amer-Indian-Eskimo' 'Asian-Pac-Islander' 'Black' 'Other' 'White']
['1' '1' '1' ... '0' '1' 

In [96]:
data = data.astype(float)
# d_male = d_male.astype(float)
# d_female = d_female.astype(float)
print(data)

[[3.90000e+01 7.00000e+00 7.75160e+04 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 [5.00000e+01 6.00000e+00 8.33110e+04 ... 0.00000e+00 1.30000e+01
  3.90000e+01]
 [3.80000e+01 4.00000e+00 2.15646e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 ...
 [5.80000e+01 4.00000e+00 1.51910e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]
 [2.20000e+01 4.00000e+00 2.01490e+05 ... 0.00000e+00 2.00000e+01
  3.90000e+01]
 [5.20000e+01 5.00000e+00 2.87927e+05 ... 0.00000e+00 4.00000e+01
  3.90000e+01]]


In [97]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.20)

In [98]:
type(test)

numpy.ndarray

In [99]:
explainer = lime.lime_tabular.LimeTabularExplainer(train ,feature_names = feature_names,class_names=class_names,
                                                   categorical_features=categorical_features, 
                                                   categorical_names=categorical_names, kernel_width=3)

Averaging the predictions to get the final model

In [100]:
def predict_fne(x):
    t = predict_fn1(x)+ predict_fn2(x) + predict_fn3(x) + predict_fn4(x)
    return t/4

In [101]:
def predicte(test):
    arr = []
    for i in range(len(test)):
        t = test[i].reshape(1,-1)
        val = predict_fne(t)
        if(val[0][1] >= 0.5):
            arr = np.append(arr, val[0][1])
        else:
            arr = np.append(arr, val[0][1])
    return arr

In [102]:
t = predicte(test)

In [103]:
from pylab import *
probs = t
# define thresholds
thresholds = arange(0, 1, 0.001)
# evaluate each threshold
scores = [sklearn.metrics.f1_score(labels_test, to_labels(probs, t)) for t in thresholds]
# get best threshold
ix = argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

Threshold=0.450, F-Score=0.66838


In [104]:
np.random.seed(m)
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(data, labels, train_size=0.80, test_size= 0.20)

In [105]:
explainer = lime.lime_tabular.LimeTabularExplainer(train ,feature_names = feature_names,class_names=class_names,
                                                   categorical_features=categorical_features, 
                                                   categorical_names=categorical_names, kernel_width=3)

In [106]:
expe = explainer.explain_instance(test[1], predict_fne, num_features=10)
expe.show_in_notebook(show_all=False)

[(10, -0.6079761202194703), (4, -0.16029739629827627), (11, -0.12504239647811086), (12, -0.09480168290666545), (5, -0.09088337442059843), (6, -0.07411391080238071), (0, -0.057287364445373724), (9, 0.052275128026544396), (13, 0.030165299080121083), (1, 0.02706895227344765)]
[1]


In [107]:
from sklearn.metrics import confusion_matrix
resulte =  confusion_matrix(labels_test, to_labels(probs, thresholds[ix]))
resulte

array([[4445,  581],
       [ 449, 1038]])

In [108]:
print("\nAccuracy is ", sklearn.metrics.accuracy_score(labels_test, to_labels(probs,thresholds[ix]))*100)
print("\n\nPrecision Value is\n", sklearn.metrics.classification_report(labels_test, to_labels(probs,thresholds[ix])))


Accuracy is  84.18547520343928


Precision Value is
               precision    recall  f1-score   support

           0       0.91      0.88      0.90      5026
           1       0.64      0.70      0.67      1487

   micro avg       0.84      0.84      0.84      6513
   macro avg       0.77      0.79      0.78      6513
weighted avg       0.85      0.84      0.84      6513



Used Submodular Pick to get the instances, then used these instances to get the global explanations for original and ensemble model respectively

In [109]:
from lime import submodular_pick
sp_obj = submodular_pick.SubmodularPick(explainer, train, predict_fn, sample_size=500, num_features=10, num_exps_desired=50)
type(sp_obj)

[(10, -0.6134171442023233), (5, -0.1843257395509945), (4, 0.1816893958359554), (11, -0.12621166366876924), (9, -0.09734275327839131), (12, -0.0898452808972982), (8, 0.05759430770912324), (13, 0.05113891548367209), (0, -0.04658881987367523), (3, -0.037648580526424384)]
[(10, -0.6349370520155574), (11, -0.13052962866432546), (9, -0.10005503297343882), (12, -0.0926772738166884), (5, -0.08903188749620829), (6, 0.06867468016067134), (8, 0.0512143382038908), (2, 0.036774126888019246), (7, -0.02914364917533042), (13, 0.028484363158915647)]
[(10, -0.6018854629806721), (5, 0.200153206090381), (11, -0.1416500558570153), (9, 0.1086029197158133), (8, 0.059698704075780554), (0, -0.055956469029576024), (13, 0.04218490645440397), (7, 0.02997785104951727), (1, 0.029233469536137768), (12, 0.026506789163229873)]
[(10, -0.6197836084840321), (5, -0.17323358951414128), (11, -0.1429231672310443), (9, -0.09049210236610171), (12, -0.08893176748872106), (4, 0.06744013787788629), (8, 0.04888351393871579), (13, 

[(10, -0.631720867069393), (5, 0.19619919772336664), (11, -0.12664816844953686), (9, 0.09444286973063618), (12, -0.0827839169894505), (0, -0.0511393968432653), (8, 0.046431496299884537), (13, 0.035876696831206624), (2, 0.02643257879092996), (6, 0.025049512496599077)]
[(10, -0.6294110364847512), (5, 0.20104267747773888), (4, 0.1983822392005034), (11, -0.1366994254619311), (9, 0.10448366375887337), (12, 0.10111728229507298), (13, 0.05825899473335925), (8, 0.05488120319222445), (7, 0.03310777459350388), (3, -0.02783802448282988)]
[(10, 0.5999657014952502), (5, 0.2024038269170879), (4, -0.16095145933436655), (11, -0.1395613634407627), (9, 0.10287793527234443), (12, -0.08445272844470167), (0, 0.07899786635814643), (6, 0.07181690357723818), (8, 0.047132408014679605), (7, 0.031654535986703584)]
[(10, -0.6123554349115937), (5, 0.20746264301867035), (4, 0.19879703943928725), (11, -0.12832867369129636), (9, 0.10122135709407501), (12, 0.0922985633924318), (0, 0.07903502861433283), (1, 0.060960022

[(10, -0.6210252211367627), (5, 0.19479052406197797), (4, -0.15666234578011162), (11, -0.14684863011976163), (9, 0.10205508955061127), (0, 0.06728300094563805), (6, 0.06566082360534625), (1, 0.06084062121579185), (8, 0.04944029694882062), (13, 0.04664843778475311)]
[(10, -0.6439228274105796), (11, -0.15641520660179098), (9, -0.09340792116681608), (12, -0.08735856984063577), (5, -0.0807794497584058), (8, -0.05671158880913031), (6, -0.05484580605969113), (7, -0.04443083259763181), (13, 0.028509912880353597), (3, -0.025805254877984084)]
[(10, -0.6144691756108625), (5, -0.17477236669144308), (4, -0.15264750106539876), (11, -0.1297340185331648), (12, 0.10511376548139126), (9, 0.10088614033894863), (7, -0.05462356202962159), (0, -0.04774337691769718), (8, 0.03206359762583229), (13, 0.025648640009256592)]
[(10, -0.6124411814141602), (5, -0.17870526974570794), (4, -0.14429913411061857), (11, -0.13154144965204922), (12, -0.09546214262047426), (9, -0.09347158953572828), (7, -0.06491237519096772)

[(10, 0.6206364539006931), (4, -0.15489230270912094), (11, -0.11376868892244875), (9, 0.08784481631601061), (5, -0.08358983977216325), (8, 0.05006742317069646), (13, 0.03213816836986005), (7, -0.030012414154431843), (12, 0.02706804528899675), (1, 0.022748822695680952)]
[(10, -0.6134076285989991), (4, 0.18710773477804513), (5, -0.17574502540568204), (11, -0.138166633795569), (12, -0.09222941015082183), (9, 0.09156885458457081), (0, -0.06326034342599954), (7, -0.061027918334469695), (6, -0.03981365639140358), (13, 0.03734712411659313)]
[(10, -0.6239837378778783), (5, -0.1835938386599745), (11, -0.13278626145526048), (9, 0.09731969851563098), (12, -0.08282478261394019), (6, 0.07859999881414588), (13, -0.0724203505269844), (7, -0.060511549254552224), (3, -0.025318061089026), (0, -0.022025475083294013)]
[(10, -0.6310229150875986), (5, 0.2010298079897361), (4, 0.1999480570527953), (11, -0.1330122281020029), (9, 0.10430299861604696), (12, -0.08945664090035876), (0, 0.06301507652808293), (8, 0

[(10, -0.6247040422648169), (5, 0.19925675725189307), (11, 0.14088450755840465), (9, 0.10940521407906202), (12, 0.0963933640873868), (4, 0.05350141344422097), (8, 0.04780552855571479), (13, 0.042284954609423005), (7, 0.03176071112482169), (1, 0.021747837205725866)]
[(10, -0.6132619224008551), (4, 0.18821208235933806), (5, -0.17276989547934032), (11, -0.1341338905965414), (9, -0.09465073680798632), (12, -0.08345220475994196), (6, 0.07818070493587399), (3, 0.07350724138261276), (8, 0.04936355461422297), (13, -0.035217780428387906)]
[(10, 0.6172828113301767), (5, 0.2007660126522231), (11, -0.17084984061002204), (9, 0.09505505683286576), (6, 0.09260219581999955), (12, -0.08851633318188916), (0, 0.06344951483127437), (8, 0.0456678405551589), (1, -0.03474093953316336), (13, 0.034549356135004906)]
[(10, -0.5993220071294361), (5, 0.19884745097276588), (4, -0.15059159883921477), (11, -0.1393260292656347), (9, 0.1006261091944582), (12, -0.08688648557676217), (0, 0.079642700501209), (3, 0.0549277

[(10, -0.6271869434555786), (4, -0.14896753388406572), (11, -0.136603851847895), (9, -0.0950134944008948), (5, -0.0899914960951323), (12, -0.08664023201194528), (0, 0.07746857140349558), (13, -0.07408269940304861), (8, 0.040954482395858735), (1, 0.027708338232088403)]
[(10, -0.6370257222537828), (11, -0.13278361679986378), (12, 0.1018660301969261), (9, -0.09861364040285989), (5, -0.0789471438233242), (0, 0.07363517508225077), (1, -0.051268854253908924), (4, 0.04935042384866453), (8, 0.04832512096582007), (7, -0.04356906247621316)]
[(10, -0.6222513295849668), (5, 0.1943722525106852), (7, 0.17509716477915557), (11, -0.12623639605038095), (9, -0.10516845849503635), (12, -0.09848076088918306), (0, -0.06079789714185241), (8, 0.04999029613292693), (4, 0.04279796460460954), (13, 0.03287150948633536)]
[(10, -0.613965959433074), (4, -0.14783513603785942), (11, -0.14527028505830122), (9, -0.10242774334860842), (5, -0.08645196892465525), (12, -0.086321506330302), (13, 0.04460429139439179), (7, -0

[(10, -0.6143074063425611), (5, -0.17301267057571046), (4, -0.14129112663659674), (11, -0.1183784976509013), (9, -0.09495377805796255), (12, -0.08339364885077558), (7, -0.05987338002782412), (0, -0.0528810706405017), (1, 0.04872499777816539), (8, 0.04133563367445502)]
[(10, -0.6248943311151792), (4, -0.15572655431394275), (11, -0.1460385554391533), (9, -0.09687018091084729), (12, -0.09178478145996423), (8, 0.04926293686477423), (13, 0.04693855926069063), (7, -0.04115642613277701), (1, 0.02959308824501709), (5, -0.0258976321697414)]
[(10, -0.613136989023262), (5, 0.2056867665376643), (4, 0.18933423782638725), (11, -0.15288470090632617), (9, 0.10287754448510061), (12, -0.0897638485656156), (6, 0.08709903881720735), (8, -0.056775913393267194), (3, -0.03369653092355105), (13, 0.03021601238106308)]
[(10, -0.6102033950903302), (4, 0.18934156602225494), (5, -0.18858017051785492), (11, -0.12248852200790364), (9, 0.09796865669551776), (12, -0.08433771744645774), (8, 0.058790096372725344), (13, 

[(10, -0.599888261069931), (4, -0.1592882256314923), (11, -0.1465378482211655), (5, -0.09147925797196167), (9, -0.09076646455012675), (12, -0.08268923108637823), (8, 0.04595250276194612), (7, -0.04081383034351552), (13, 0.03231262693317236), (1, 0.022532413490566863)]
[(10, 0.6297620078192342), (5, -0.16954837088438016), (4, -0.15620194791504508), (11, -0.12404723660078211), (9, 0.09398388340007119), (12, -0.08535269200454537), (0, -0.05325298478024732), (7, -0.052254712907607075), (8, 0.04272743053043671), (13, 0.039656854131995684)]
[(10, -0.6164772502577602), (5, 0.19275006790372762), (11, -0.14355174968443063), (9, 0.0996600935475326), (12, -0.08769677790426295), (0, 0.05720393862418362), (4, 0.048263787165699276), (8, 0.03900308315528388), (13, 0.03422023552710533), (1, 0.026725555572113476)]
[(10, -0.606613336728895), (5, 0.19964316022852754), (4, -0.15613347981096568), (11, -0.1354367824108368), (12, 0.0981752428359475), (9, 0.09076522887945285), (1, -0.06764060792244225), (0, -

[(10, -0.6285597737946075), (5, 0.19314463072761284), (4, -0.15839191039768477), (11, -0.122107781585486), (9, 0.10416569711257997), (12, -0.09116933407306811), (8, 0.058695203475263046), (13, 0.0296499659099658), (0, -0.024827499341274047), (6, -0.02287636905929357)]
[(10, -0.6114049819116251), (5, 0.19494986717774793), (4, -0.15843607584217922), (11, -0.12857449077440034), (9, 0.10585792054588916), (12, -0.09352899505687104), (13, 0.04959686588214726), (8, 0.045838360422716655), (1, 0.0365081580391453), (0, -0.02613871751200892)]
[(10, -0.6020063363339306), (5, 0.2047493455611236), (4, 0.19808937007725683), (11, -0.15493624577281012), (9, 0.09806355798617436), (6, 0.0843243132994516), (0, 0.07879467394046506), (8, 0.05327862616778659), (13, 0.03933880710217202), (1, 0.02189430341298653)]
[(10, -0.6488630410249403), (5, 0.20601329635583407), (4, -0.15921445632083064), (11, -0.1313435906503263), (12, 0.09264418308653533), (9, 0.09228700153752065), (8, 0.04957116596325655), (6, -0.03888

[(10, -0.621884195893308), (5, 0.19956152870285931), (11, 0.13417492098404313), (9, 0.09371537987279153), (12, 0.09180547499635353), (0, 0.07419602454045393), (6, 0.07262205011097751), (8, 0.04434847856597416), (13, 0.03532174115552304), (3, -0.030144167228093016)]
[(10, 0.5966333774161745), (4, 0.1972109938850353), (11, -0.12386639353689065), (9, -0.10046260958197173), (12, -0.0941909984775059), (5, -0.07492834586545087), (13, 0.0401562637251862), (8, 0.03997886669515726), (1, -0.038649908668663475), (3, -0.03672053065509066)]
[(10, -0.6145611494928401), (5, 0.20109352198445696), (7, 0.1691352775263473), (4, -0.15310335273137385), (11, -0.1429532690105691), (9, -0.09514796566023878), (12, -0.09466520383051548), (8, 0.05955835627672614), (13, 0.026582903998752433), (3, -0.022753985526105715)]
[(10, -0.622053887514352), (5, -0.1766889756832252), (11, -0.1270454417642417), (9, 0.10279665979035627), (12, -0.0903749910767907), (6, -0.07300774919885407), (4, 0.04892506500684857), (0, -0.045

[(10, -0.6218213986057263), (4, 0.20221166240047264), (5, -0.18023874745561305), (11, -0.15900522648081675), (9, 0.10464384427657943), (12, -0.0921162152703847), (8, -0.0660125449010021), (13, 0.04121385260887284), (7, -0.03582389148276818), (3, -0.032240067834561285)]
[(10, -0.6142539576936163), (5, 0.1937844797501222), (4, -0.1543468162092451), (11, -0.15391691193567567), (9, 0.10422047820331977), (12, -0.10186663318152374), (8, 0.051172925666792796), (13, 0.040171526685033807), (7, 0.024553520568548308), (1, 0.019007510713905836)]
[(10, 0.6290795777900603), (5, 0.2020442169762142), (4, 0.1893510940203022), (11, -0.13242674762978296), (9, 0.1030179546047424), (12, -0.0970631287215871), (0, 0.07139825897665497), (1, 0.06586920559597045), (8, 0.04894451834856915), (13, 0.03340164920946154)]
[(10, -0.6170970076231349), (5, 0.1924570175810292), (11, -0.15548974630743942), (12, 0.10807550702509436), (9, 0.09833596714983656), (0, 0.0733420530017042), (6, 0.07017702339570817), (8, 0.0499429

[(10, -0.6211884068021893), (5, 0.20414500245102457), (4, -0.15403990357759456), (11, -0.13427844259846622), (12, 0.1023119654390452), (9, 0.1005177357844553), (8, 0.05758756968200182), (13, 0.03200403582133867), (7, 0.02447466407371588), (0, 0.020376173927296574)]
[(10, -0.6247648640388954), (11, -0.12630072227621306), (9, -0.093634317624029), (12, -0.0926126530045569), (5, -0.08160976752737738), (6, 0.06959583659354464), (8, 0.04988184220949519), (13, 0.03732757397499933), (7, -0.03404598403480334), (3, -0.022437226936605378)]
[(10, -0.6136682560063036), (5, 0.20193518255014148), (11, -0.1454901762599473), (12, 0.10775999658319176), (9, 0.10651890801069687), (1, -0.07352493433037297), (4, 0.053707814656637806), (13, -0.03974534999232011), (3, 0.03898150918889826), (8, 0.03896573318977501)]
[(10, -0.6253069185945036), (11, -0.12300532258925799), (9, -0.10869717395101466), (12, -0.09426046045387089), (5, -0.09349277658746798), (4, 0.04804508094893764), (8, 0.04749764617890224), (7, -0.

[(10, -0.6266065999577849), (4, 0.18944908250574127), (11, -0.14926738325898614), (9, 0.09992219542794573), (12, -0.09646672659205101), (5, -0.09355243464712817), (8, 0.04733591961353361), (3, 0.043678212718946945), (7, -0.026740711791898724), (1, -0.024456182979989347)]
[(10, -0.6376816663303068), (5, 0.20005160905322963), (11, -0.1512282926843155), (12, -0.10767851507657811), (9, 0.09446209483489483), (0, 0.07314404348183755), (6, 0.06906329128769403), (8, 0.05513720772337363), (4, 0.05013294418430114), (13, 0.03740178518129699)]
[(10, -0.6283598194592376), (4, 0.19255202212644854), (5, -0.1672874785184295), (11, -0.10951128102527202), (9, -0.10036275331532912), (12, -0.0919701800433475), (0, -0.045648578855067005), (13, 0.04473046644185806), (8, 0.043071208065515836), (3, -0.04149580962404092)]
[(10, -0.6571405061001313), (5, -0.17631245790604783), (4, -0.14883819262863862), (11, -0.1284304720979018), (9, -0.09287139243066096), (12, -0.08161390675645112), (8, 0.0488832752462413), (1

[(10, -0.623283245286485), (5, -0.17507555095037233), (4, -0.14557947113454608), (11, -0.11660513128425296), (9, -0.09867452314765346), (12, -0.0899705487733458), (0, -0.05082730802263654), (7, -0.047190456168414746), (8, 0.04648135888966609), (13, 0.03710337407557096)]
[(10, -0.6278156050010545), (5, -0.17348055583493702), (4, -0.15344353682271994), (11, -0.11755752842211417), (9, 0.09797702019888423), (12, -0.08474314854814916), (3, 0.07747725185140798), (0, -0.05540367265213703), (13, -0.04712884605170497), (8, 0.035996547278038936)]
[(10, -0.6172841420968148), (5, 0.1901230651163696), (4, -0.15902112967976806), (11, -0.13968215447826623), (12, 0.09660965262149328), (9, 0.09157487200546406), (3, 0.07251309371122361), (13, -0.06621784854545452), (8, 0.052997291378548146), (6, -0.025013253427527866)]
[(10, -0.6213836576673855), (5, 0.1979057446452129), (4, 0.182270839011056), (11, -0.133010498627174), (12, 0.1026949501029229), (9, 0.10146168033088751), (1, -0.08003536002016114), (8, 0

[(10, -0.606923097499114), (5, 0.20930483733181554), (11, -0.13696806374323545), (9, 0.09854375724251244), (12, -0.09537679023557821), (0, 0.07997212095714215), (8, 0.04430487774676467), (13, 0.04214311637771389), (3, -0.03527703699315177), (6, 0.03374313829610446)]
[(10, -0.6338201435229271), (4, 0.1873062370359755), (5, -0.1790137388783914), (11, -0.1385341947502492), (9, 0.09722873740929641), (12, -0.09397794213780156), (7, -0.05826412470013338), (0, -0.05130803328224237), (8, 0.03772179118326752), (1, 0.03269633335982334)]
[(10, -0.5941411312257019), (4, 0.19363109497385536), (5, -0.1819113540099224), (3, 0.13112248354411946), (11, 0.13035616290127694), (9, 0.09450943550642339), (1, -0.07360285970944848), (8, 0.05019247806964756), (13, 0.034096318520969095), (12, 0.031155107076743706)]
[(10, -0.6123898166119495), (4, -0.15137775985543223), (11, -0.13989530680015047), (12, -0.08772716121822968), (9, -0.08482457134508721), (1, 0.07741138887252788), (0, 0.07688406955171513), (6, 0.071

[(10, -0.6527399878657631), (4, -0.15334985729072295), (11, -0.13352170803602856), (9, 0.0993668675701617), (12, -0.08653274244798795), (0, 0.06918541921947208), (3, 0.05612847413320814), (8, 0.04333885717011039), (13, 0.03250201047445931), (7, -0.027557330910481126)]
[(10, -0.6053637517873156), (5, 0.19711287150708562), (4, 0.19703986553384523), (11, -0.12356725887447331), (9, 0.10060109486231172), (12, -0.09544850431555699), (0, 0.07708737756030089), (6, 0.07049512055857936), (8, 0.043854864489535184), (13, 0.04095565747443296)]
[(10, -0.6182229518392623), (5, 0.19900935025128025), (4, 0.1919806841234434), (11, -0.15555623457490217), (9, 0.10054614921850905), (12, -0.09189244239460743), (8, 0.045597263967711854), (13, 0.0342438636293512), (7, 0.029999625398364083), (2, -0.0229459335748454)]
[(10, -0.62895282611373), (5, 0.21101816940038362), (11, -0.1416841964949947), (12, 0.11899755390419967), (9, 0.10732516439559321), (13, 0.051109107464552314), (8, 0.050680296739473184), (1, 0.031

lime.submodular_pick.SubmodularPick

In [110]:
from collections import Counter
a = Counter()
for i in sp_obj.V:
    exp = sp_obj.explanations[i]
    a1 = Counter(dict(exp.local_exp[1]))
    a.update(a1)

In [111]:
ans_data = []
for key in a:
    ans_data1 = []
    ans_data1.append(feature_names[key])
    ans_data1.append(a[key])
    ans_data.append(ans_data1)
df = pd.DataFrame(ans_data, columns = ["Feature", "Contribution"])
sumdf = df['Contribution'].sum()
df['Contribution'] = df['Contribution']
df

Feature  Contribution
0     Capital Gain    -23.792107
1   Marital Status      2.116016
2    Education-Num     -1.573597
3     Capital Loss     -6.469338
4              Sex      1.804058
5   Hours per week     -2.496092
6              Age      0.698024
7             Race      1.927533
8          Country     -0.117665
9        Workclass     -0.070857
10      Occupation     -0.066678
11    Relationship      0.235550
12       Education      0.667795
13          fnlwgt     -0.012202

#### Explanation for original model (Note: We only consider top 10)

In [112]:
df.iloc[(-np.abs(df['Contribution'].values)).argsort()]


Feature  Contribution
0     Capital Gain    -23.792107
3     Capital Loss     -6.469338
5   Hours per week     -2.496092
1   Marital Status      2.116016
7             Race      1.927533
4              Sex      1.804058
2    Education-Num     -1.573597
6              Age      0.698024
12       Education      0.667795
11    Relationship      0.235550
8          Country     -0.117665
9        Workclass     -0.070857
10      Occupation     -0.066678
13          fnlwgt     -0.012202

In [113]:
from lime import submodular_pick
sp_obj = submodular_pick.SubmodularPick(explainer, train, predict_fne, sample_size=500, num_features=10, num_exps_desired=50)
type(sp_obj)

[(10, 0.6381710548969938), (4, -0.156212270927697), (11, -0.11621245296039799), (7, -0.1128519123324365), (12, -0.08932689471243756), (5, -0.07811718945278498), (0, -0.06523393887399884), (9, 0.037527836756478465), (13, 0.024029742618161286), (2, -0.020972620392572014)]
[(10, -0.6262807087573802), (11, -0.15447186667516072), (12, -0.0887473478895777), (7, -0.07953297267715156), (5, -0.07774952519078984), (6, -0.07330971727787554), (9, 0.03903953118069666), (13, 0.030639023507829703), (0, -0.02293480439689863), (8, 0.01394595260920844)]
[(10, -0.60622701442585), (11, -0.1378498875852266), (7, -0.08863070237792954), (12, -0.0862406713178634), (6, 0.07803685852013485), (5, -0.07750612561846992), (9, -0.035446733175692774), (13, 0.035338906768702015), (2, 0.026542558204306985), (8, 0.022574962760410044)]
[(10, -0.6117476321044457), (4, -0.1552532269262953), (11, -0.13692633323742165), (0, 0.08752593226059494), (7, -0.0845867603691956), (12, -0.08398962915639269), (1, 0.06516218719605761), 

[(10, -0.6123302545334505), (4, -0.15043191570856582), (7, -0.13329130292948843), (11, -0.114071453444828), (12, -0.09028514870021677), (5, -0.08146326837542069), (9, -0.05108107106875722), (13, 0.03735977294516757), (8, 0.019743046158974716), (1, 0.0188652136484884)]
[(10, -0.6226513933888985), (4, -0.14903292056606768), (7, -0.09432247932222781), (11, -0.09341094359716384), (12, -0.08772644103739867), (9, 0.04931173356386163), (5, -0.04494091001941492), (13, 0.0447303759969647), (6, -0.03503095097383748), (0, -0.02284779774501258)]
[(10, -0.5955946636843008), (4, 0.1997649088452114), (11, -0.12866069183516682), (12, -0.09956547692154132), (7, -0.09521321388135907), (9, -0.05530447577072088), (5, -0.049238095624130215), (13, 0.02438038965989121), (2, -0.024322985664102535), (0, -0.019880902448435142)]
[(10, -0.6227574848162698), (11, -0.13665518124759465), (7, -0.08843858367430579), (12, -0.08806366235059052), (0, 0.08237412310379108), (9, -0.05228659840330493), (5, -0.040273783855969

[(10, -0.6175021842545512), (4, -0.15519091910026464), (11, -0.14109162399932582), (7, 0.12558825079879235), (5, 0.10208889852847763), (12, 0.09546002749369294), (1, -0.05934187931176626), (9, 0.04812104058493722), (13, 0.02954040381411462), (0, -0.028945868787193213)]
[(10, -0.6262590451022413), (11, -0.11751430802081023), (12, -0.09368831920898016), (7, -0.0841190360811431), (0, 0.06412132357540495), (4, 0.05619798031874494), (9, -0.03869274106844882), (6, -0.02375665229983592), (3, -0.02239499182190116), (13, 0.020925126221563603)]
[(10, -0.6215750292705016), (11, -0.1396977825453155), (7, 0.12642219256093398), (5, 0.10046917862567295), (12, -0.09230133553666955), (9, 0.05286509273460527), (4, 0.05171983692292842), (13, 0.026195971859454048), (1, 0.02291352056536586), (8, 0.020397192916484664)]
[(10, -0.6207400917324569), (7, 0.12375255315629177), (11, -0.10708187827355592), (5, 0.09908784898543194), (0, -0.07149561303036005), (9, 0.04499735001468786), (6, 0.04423093680347097), (4, 

[(10, 0.6245527186609031), (11, -0.14014531473883574), (7, -0.09059154069762738), (12, -0.08638321431306072), (4, 0.05691308501149645), (9, -0.04433170119613684), (1, -0.041133401928130905), (5, -0.0411321865573314), (3, -0.03542541489007785), (6, -0.03104314135351546)]
[(10, -0.6002138637011584), (4, -0.15690550817920662), (11, -0.14159811273952577), (12, -0.09065572938353017), (7, -0.08576266152923571), (6, -0.07965772039262532), (9, -0.051315731293547884), (3, 0.038624636290501654), (13, 0.03418848904190818), (1, 0.018840448613306665)]
[(10, -0.6170942745027592), (4, 0.1982412508978434), (7, 0.1319518251912277), (11, -0.1304507581982894), (5, 0.10291026614965695), (12, -0.08977832212699344), (0, 0.07314420710934202), (9, 0.05329575225581573), (8, 0.03910336310746966), (3, -0.025702083457360254)]
[(10, -0.6285197512777105), (4, 0.18666722177624587), (11, -0.11785656825626761), (12, 0.09489495521264733), (7, -0.09292065467642735), (0, 0.09017937127315598), (5, -0.08583287685636631), (

[(10, -0.6147562883254394), (4, -0.1530167649647965), (11, -0.11331125372717091), (7, -0.1115129095256295), (5, -0.08935166965836094), (12, -0.08603156029163365), (6, -0.08588385865484989), (0, -0.05082017565823747), (9, 0.047765383370048306), (3, -0.02442890493834223)]
[(10, -0.6303888247519889), (4, -0.15475426758371644), (11, -0.1405640824241524), (12, 0.10438393138926286), (5, -0.04710333046398591), (9, -0.045595482295805796), (0, -0.029788000205411846), (13, 0.02807502204673037), (2, 0.021384723046617777), (3, -0.018138937657744197)]
[(10, -0.6303112611222953), (11, -0.13168686098123772), (7, -0.08626392928129831), (5, -0.08150723230234419), (12, -0.0786572696844723), (9, -0.045583433622490004), (1, -0.02085188919840425), (13, 0.019830610795271115), (0, -0.018951005649277465), (3, -0.018308690566794326)]
[(10, -0.609519152758016), (11, -0.1284415529559677), (5, -0.09044485337606445), (7, -0.08952030314346959), (9, 0.06042131825992382), (0, -0.05413065270197815), (13, 0.02558535969

[(10, -0.6264569152799323), (4, -0.16085371928739337), (11, -0.1413520590760718), (7, 0.12744385805268144), (12, -0.09125034932748126), (5, 0.08912458599419133), (0, -0.06523918211931569), (9, 0.039848552720946395), (13, 0.028612202184648525), (1, 0.018230330207369937)]
[(10, -0.5909409241259674), (11, -0.10983124403781758), (12, 0.10070025967503451), (7, -0.09599521183907332), (0, 0.08979669694793102), (6, 0.07763036498443447), (9, -0.04704993844410342), (5, -0.04167656730143395), (13, 0.037000561499747585), (1, 0.02480573050779964)]
[(10, -0.641227377588749), (11, -0.13392973397062966), (7, -0.12352314331395974), (6, -0.09207169505704699), (5, -0.07902671439933641), (12, -0.07731664976758462), (0, -0.05975863318311483), (9, -0.04094655450434794), (2, -0.017652929840133218), (3, -0.01324719090883853)]
[(10, -0.6277519609168122), (11, -0.15168187071577094), (4, -0.1514252870083614), (12, -0.09568945677790575), (7, -0.0856105894168063), (0, -0.05167102771952353), (9, -0.0446798644332294

[(10, -0.6373159747727019), (4, -0.15748542592820858), (7, 0.12713682418784122), (11, -0.12183956126876958), (12, 0.09778011445399279), (5, 0.09565439783828429), (0, -0.0650384202175301), (9, 0.052772778980903455), (13, 0.0386167510027484), (6, -0.03766256947515204)]
[(10, -0.6020110839328661), (4, 0.1958904384930863), (11, -0.12099086684967073), (7, -0.08849626882414795), (12, -0.08389426528958514), (5, -0.07952735444843315), (6, 0.0656403894212669), (0, -0.058197700767377625), (9, -0.04865153158949461), (13, 0.030407544132136484)]
[(10, -0.5978527713065392), (4, -0.1526770151205412), (11, -0.1340853796192215), (7, 0.11412909681379912), (5, 0.10493454819930617), (12, -0.09038356309814244), (9, 0.044488556360631926), (0, -0.029339993508096174), (1, 0.02834855283038317), (13, 0.027597084580917766)]
[(10, -0.6402700174955656), (4, -0.1602300440932899), (11, -0.15053518393058582), (7, 0.12870500823182035), (5, 0.10410942293184232), (12, -0.0998699434800791), (1, 0.07710948168595369), (3, 

[(10, -0.6333008882167456), (11, -0.12811614438357036), (7, 0.12777192331849924), (12, 0.10462416206700834), (5, 0.10403595297292685), (0, 0.07663497065413699), (1, -0.058793679076991706), (9, 0.052752991891903155), (13, 0.026129918509684418), (8, 0.019919926064850088)]
[(10, -0.612146869866667), (4, -0.15486392376773897), (11, -0.1256363082746667), (12, -0.09757225897446482), (5, -0.08865307592157771), (3, 0.07223110820960865), (13, -0.06133798813621092), (0, -0.05935950890123009), (9, 0.046015113264553355), (6, -0.030411071874873526)]
[(10, -0.6189219529487663), (7, 0.2378543854213954), (11, -0.13635190226344773), (5, 0.10105086081930109), (12, -0.08587833340635762), (6, 0.07296623152813089), (4, 0.05338848758955741), (3, -0.04845844385829084), (9, -0.04562639672969337), (0, -0.031790760396614194)]
[(10, -0.6191066060861968), (4, -0.14958070800965886), (11, -0.10268843457431813), (12, -0.09533381170963502), (7, -0.07691180831281069), (5, -0.0441804088679034), (9, -0.03597124751273474

[(10, -0.6116323140260072), (4, -0.15179416078278296), (11, -0.14080207624346072), (7, 0.11803885858615369), (5, 0.10617502875077443), (12, 0.09515697757706247), (6, -0.07287507459920563), (9, 0.056802407486362595), (2, -0.023438071139000833), (8, -0.02018808346445267)]
[(10, -0.5828913684316707), (4, -0.15234711343686247), (11, -0.13353962457073304), (12, -0.08910017173978982), (0, 0.08581265362451661), (7, -0.08392855347562475), (1, 0.06557183032669943), (6, 0.06279375778103755), (9, 0.04776525814541365), (5, -0.0464412128316801)]
[(10, -0.6195199242165293), (4, 0.19075277010051128), (7, 0.13328418787730423), (11, -0.12497839627740763), (5, 0.11059922256977471), (12, 0.10336678854742193), (9, 0.04903894618544508), (13, 0.027390992231294528), (3, -0.022621180309483613), (1, 0.0158251640251532)]
[(10, -0.623957337986775), (4, 0.2002074457734905), (7, 0.1268360588160516), (11, 0.12614152659886638), (5, 0.09822667520459297), (12, -0.08969638446609828), (1, 0.08655531049754557), (6, 0.062

[(10, -0.634082034464011), (4, -0.14361587400638887), (11, -0.12010627988462), (12, -0.08817579876738758), (7, -0.08361756431258166), (9, -0.04787186631677202), (1, -0.03766928740643475), (5, -0.03227506205747353), (13, 0.03046957826014148), (6, -0.02565958624916231)]
[(10, -0.6205309959901097), (4, -0.1547063207184309), (11, -0.14649924019844057), (12, -0.09966234341864), (7, -0.08583907751205191), (0, 0.08021214221973212), (9, -0.043931728649587), (6, -0.037423367818068445), (1, -0.0341128301552421), (13, 0.03287802093426212)]
[(10, -0.6055227809361298), (11, -0.14186349888760771), (12, 0.09884759009701205), (6, 0.07721896622089877), (9, 0.0553837853207886), (5, -0.048803838421598314), (0, -0.0371191901923272), (1, 0.017567525476143788), (3, -0.01694701580733953), (13, 0.014280303837786525)]
[(10, -0.6199143811183362), (11, -0.1561197725108975), (4, -0.15301945914220821), (12, -0.09514488360546748), (7, -0.09302120650789722), (9, 0.04336568150779923), (5, -0.0429285737452918), (13, 0

[(10, -0.6208507380815333), (11, -0.11876161354202033), (12, -0.09653068660872088), (6, -0.08123901478293129), (9, 0.04875643639947433), (13, -0.02609384765507256), (2, 0.02474766351023705), (0, 0.021732768014666504), (1, -0.01628511073127122), (8, -0.015333269741376563)]
[(10, -0.6254402675829163), (4, -0.15792349804804548), (11, -0.13426646384756602), (7, 0.12570830525145843), (5, 0.10882976441817002), (12, -0.09924420746441297), (0, -0.058357420473474), (9, 0.04609812979555671), (6, -0.043699156056474356), (13, 0.02966434314569216)]
[(10, -0.610334371822563), (4, 0.1987254332934587), (11, -0.1577790644043964), (7, 0.1336077011461324), (5, 0.10185012213976392), (12, -0.09257979012390379), (9, 0.05005691540781077), (6, 0.026839607673399556), (2, -0.022846454306469043), (8, -0.020868748675336772)]
[(10, -0.6216715823523217), (4, 0.1999227574407076), (7, 0.1304062008748421), (11, -0.1123869010199732), (12, 0.10267519557252655), (5, 0.09972127579427786), (0, 0.08109096939102202), (6, 0.0

[(10, -0.6276574551066015), (11, -0.1307461839316739), (7, -0.1132342412072928), (12, -0.08461710936138139), (5, -0.08209720548473655), (0, -0.06315462670389353), (9, -0.047591295984632895), (13, 0.04099013849603063), (2, 0.020993954220240408), (6, -0.01665972306207844)]
[(10, -0.6045204162351617), (4, -0.16398582338049714), (7, 0.13591770815582108), (11, -0.1152828671248673), (5, 0.09983915337520086), (12, -0.09117330641048534), (9, 0.04981582087157224), (6, -0.04270308168995474), (13, 0.03605695261867747), (3, -0.017645121864190108)]
[(10, -0.6183172333515631), (4, -0.1590347757490675), (7, 0.13507731039247686), (11, -0.13292901095692516), (12, -0.10121490119031334), (5, 0.09487845670894793), (0, 0.08770221691206904), (1, -0.05113984869062036), (6, -0.04312466571812051), (9, 0.04186194465879338)]
[(10, -0.6391971302857846), (11, -0.1450167845333043), (7, -0.09127764154826924), (5, -0.08556444254419454), (12, -0.08280154400171565), (0, -0.06801174727926569), (9, 0.040019662331989704),

[(10, -0.617926971121554), (4, -0.15850550550110867), (11, -0.1396446712745067), (7, 0.12571138618708005), (5, 0.1077268879430317), (12, -0.10014744483364572), (0, 0.08637508796016466), (9, 0.04437473603177142), (3, 0.04426902962590471), (13, 0.035149796644512746)]
[(10, -0.6124925557294697), (4, -0.15680396821616246), (11, -0.14615752438241625), (7, -0.1175519033925575), (5, 0.09947281502748821), (12, -0.09229722771024473), (0, -0.050214709696916396), (6, -0.03976545941070724), (9, 0.0379057214641428), (13, 0.027792582714353576)]
[(10, -0.6185033874595249), (4, -0.15908013330209772), (11, -0.1504890563819976), (7, 0.12958706627493233), (5, 0.09519441405431234), (0, 0.0786245047796998), (9, 0.049899541896622615), (13, 0.03184245617810329), (2, 0.02477126074924994), (1, 0.020376038415050837)]
[(10, -0.6160928661718518), (11, -0.11451716102160102), (12, 0.1075379093227941), (7, -0.0843077951578195), (6, -0.06686640526142182), (9, -0.05032282292088415), (1, 0.028607055602061244), (13, 0.0

[(10, -0.6061083367111422), (4, -0.15806258086888003), (11, -0.1461328948087448), (7, -0.12989206707387121), (5, -0.09024702437773006), (12, -0.08616096304404361), (0, -0.050008809451480674), (9, 0.04493755981509141), (13, 0.014909215111029345), (1, 0.014020194938925378)]
[(10, -0.61173523146436), (4, 0.1940374873231391), (11, -0.15131712481968107), (7, 0.12766219399202164), (5, 0.10322182720475033), (12, -0.1010785738344224), (1, -0.06741219694427572), (9, 0.047143618826985575), (13, 0.02965217673709807), (3, -0.02437415418972952)]
[(10, -0.6293639176814905), (4, 0.18471330300349392), (11, -0.11863826308122524), (12, -0.08966194805764986), (5, -0.08526812295429316), (7, -0.0770303163280023), (0, -0.05345802312416926), (9, -0.03952423184198659), (6, 0.021961077606887484), (13, 0.01900231338134458)]
[(10, -0.5824649716543773), (11, -0.11936474184837452), (7, -0.11821432228130965), (12, -0.10245285907701505), (5, -0.08900348522858212), (0, -0.05585424625013591), (9, 0.05226467254498519),

[(10, -0.6023500640625822), (11, -0.155457657279605), (12, -0.08912622742931739), (5, -0.07369608892746436), (0, -0.05283389359246944), (13, 0.039864388031703564), (9, 0.03888554828331457), (2, 0.02313079382720498), (1, 0.02212979067300925), (4, -0.0113403102248093)]
[(10, -0.6285627892769577), (7, -0.12974493382117988), (11, -0.11781588863943275), (12, -0.1061077558065779), (5, -0.08277998130279422), (0, -0.0570930551946651), (9, 0.04572586911122372), (6, 0.03399737131921528), (13, 0.03193225813614902), (2, 0.029046927079815345)]
[(10, -0.6239214958676758), (4, 0.19671954412274814), (11, -0.14372007446733848), (7, 0.12246997837806785), (5, 0.10490112493071495), (12, 0.10283097020880225), (6, 0.09303820989059279), (1, 0.07854814215500851), (9, 0.04725043481139122), (0, -0.025715266008681632)]
[(10, -0.5850113960539112), (11, -0.13600637359886733), (7, -0.12094391349921278), (5, -0.09045432533953247), (12, -0.09020032162849684), (0, -0.05974717539853993), (9, -0.054333215408583914), (13

[(10, -0.6038417756482374), (11, -0.13357193538639361), (7, 0.12384377658148396), (12, 0.10777928807595513), (5, 0.10375691340078252), (0, -0.05869087743385858), (6, -0.05049437764392483), (9, 0.04520412629249924), (13, 0.026505553737376182), (8, 0.017105120877169398)]
[(10, -0.6255593207269045), (11, -0.14865144536264951), (7, -0.09354860779359407), (12, -0.08700186655743561), (5, -0.07834075338071836), (0, 0.07121279021006681), (9, -0.042445631963082056), (1, -0.03761094589830343), (8, -0.02624676206163123), (13, 0.023870601688482162)]
[(10, -0.6113905103365892), (4, -0.15119250281166152), (11, -0.14384481251308517), (7, -0.1192707735126224), (12, -0.08509379105878327), (6, -0.08415739733467013), (5, -0.07926994380591124), (0, -0.05910359717044176), (9, 0.04498843654353747), (13, 0.03208645117275655)]
[(10, -0.6122372735053071), (4, 0.18177372751773732), (11, -0.12397349739967713), (5, -0.09461784806641356), (12, 0.08849492172557523), (7, -0.08270772833655846), (9, -0.042336886683858

lime.submodular_pick.SubmodularPick

In [114]:
from collections import Counter
a = Counter()
for i in sp_obj.V:
    exp = sp_obj.explanations[i]
    a1 = Counter(dict(exp.local_exp[1]))
    a.update(a1)

In [115]:
ans_data = []
for key in a:
    ans_data1 = []
    ans_data1.append(feature_names[key])
    ans_data1.append(a[key])
    ans_data.append(ans_data1)
#     print(feature_names[key] )
df = pd.DataFrame(ans_data, columns = ["Feature", "Contribution"])
sumdf = df['Contribution'].sum()
df['Contribution'] = df['Contribution']
df

Feature  Contribution
0     Capital Gain    -23.543842
1     Capital Loss     -5.767617
2    Education-Num     -1.673827
3     Relationship      0.065351
4   Marital Status      0.028490
5   Hours per week     -1.541263
6       Occupation     -0.062209
7              Age     -0.242858
8              Sex      0.477145
9          Country      0.802061
10       Workclass      0.426351
11            Race     -0.021671
12       Education      0.547427
13          fnlwgt      0.025978

#### Explanation for LimeOut's Ensemble model (Note: We only consider top 10)

In [116]:
df.iloc[(-np.abs(df['Contribution'].values)).argsort()]


Feature  Contribution
0     Capital Gain    -23.543842
1     Capital Loss     -5.767617
2    Education-Num     -1.673827
5   Hours per week     -1.541263
9          Country      0.802061
12       Education      0.547427
8              Sex      0.477145
10       Workclass      0.426351
7              Age     -0.242858
3     Relationship      0.065351
6       Occupation     -0.062209
4   Marital Status      0.028490
13          fnlwgt      0.025978
11            Race     -0.021671

**a array has the accuracies for original model (calculated over 30 times)
b array has the accuracies for Ensemble model (calculated over 30 times)
Applied statistical t-test to see if their mean is significantly different. And verify that improvement in accuracy for Ensemble is significant**

In [117]:
a = [
82.65008444649163,
81.42177184093352,
82.6040227237832,
84.86027228989661,
82.35233903163068,
82.42399426758112,
82.42399426758112,
82.71061521138294,
83.03818200429932,
82.22950148428703,
82.59801412631795,
83.46811342000204,
82.21926502200839,
82.39328488074521,
83.26338417442932,
83.35636419468754,
83.11070167357593,
84.50790726239829,
83.50990327038231
]

In [118]:
b = [
81.97451251343468,
81.97451251343468,
82.65008444649163,
82.47517657897431,
82.46494011669567,
84.1539563926707,
84.1539563926707,
83.28385709898659,
84.45081379875116,
82.43423072985976,
82.34210256935202,
82.38304841846657,
83.22243832531477,
81.9121711536493,
83.58071450506705,
83.38622172177296,
81.1761093198219,
82.40442192538,
81.92845079072623
]

In [119]:
c = [
84.18547520343928,
84.60003070781514,
84.79963150621833,
83.89804483570478,
84.53270549698024,
84.47128672330842,
84.47128672330842,
83.63189681646023,
82.9767632306275,
82.58777766403931,
82.73108813594023,
83.60118742962432,
83.7342614392466,
82.58777766403931,
83.69331559013206,
84.14371993039205,
84.14371993039205,
82.97251650545063,
82.77291570704745
]

In [120]:
import scipy

In [121]:
scipy.stats.ttest_rel(a, b, axis=0, nan_policy='propagate')

Ttest_relResult(statistic=0.5163613830939042, pvalue=0.6118875682721937)

In [122]:
def remove_exponent(value):
    decial = value.split('e')
    ret_val = format(((float(decial[0]))*(10**int(decial[1]))), '.8f')
    return ret_val

In [123]:
scipy.stats.ttest_rel(b,c, axis=0, nan_policy='propagate')

Ttest_relResult(statistic=-3.899338846121264, pvalue=0.0010509638832705236)

In [124]:
scipy.stats.ttest_rel(a,c, axis=0, nan_policy='propagate')

Ttest_relResult(statistic=-2.8839235500158766, pvalue=0.009882440624063427)